---

# file: roles/postgresql/defaults/main.yml

postgresql_contrib: "true"
postgresql_dbencoding: "UTF8"
postgresql_dblocale: "en_US.UTF-8"
postgresql_dbcollate: "en_US.UTF-8"
postgresql_dbctype: "en_US.UTF-8"
postgresql_dbowner: "zabbix"
postgresql_dbtemplate: "template0"

postgresql_extensions:
 - pg_stat_statements
 - pg_buffercache
 - adminpack
 - pg_prewarm
 - pgstattuple 

postgresql_cluster_location: /data/db
postgresql_drop_old_cluster: "true"
postgresql_default_unix_auth_method: "trust"
postgresql_default_ipv4_auth_method: "md5"
postgresql_default_ipv6_auth_method: "md5"

postgresql_pg_hba_default:
 - { type: local, database: all, role: "{{ postgresql_admin_user }}", address: "",             method: "{{ postgresql_default_unix_auth_method }}", comment: '"local" is for Unix domain socket connections only' }
 - { type: host,  database: all, role: all,                           address: "127.0.0.1/32", method: "{{ postgresql_default_ipv4_auth_method }}", comment: 'IPv4 local connections:' }
 - { type: host,  database: all, role: all,                           address: "0/0",          method: "{{ postgresql_default_ipv4_auth_method }}", comment: 'IPv4 remote connections:' }
 - { type: host,  database: all, role: all,                           address: "::1/128",      method: "{{ postgresql_default_ipv6_auth_method }}", comment: 'IPv6 local connections:' }

postgresql_conf_listen_addresses: "'*'"
postgresql_conf_shared_preload_libraries: "'pg_stat_statements'"
postgresql_conf_shared_buffers: '{{ ( ansible_memtotal_mb / 4 )|int }}MB'
postgresql_conf_work_mem: 8MB
postgresql_conf_effective_cache_size: '{{ ( ansible_memtotal_mb / 2 )|int }}MB'
postgresql_conf_max_files_per_process: 10000
postgresql_conf_bgwriter_delay: 10ms
postgresql_conf_bgwriter_lru_maxpages: 1000
postgresql_conf_bgwriter_lru_multiplier: 10.0
postgresql_conf_wal_level: hot_standby
postgresql_conf_fsync: on
postgresql_conf_synchronous_commit: on
postgresql_conf_full_page_writes: on
postgresql_conf_archive_mode: on
postgresql_conf_archive_command: "'/bin/true'"
postgresql_conf_checkpoint_segments: 32
postgresql_conf_checkpoint_timeout: 60min
postgresql_conf_checkpoint_completion_target: 0.9
postgresql_conf_max_wal_senders: 6
postgresql_conf_wal_keep_segments: 64
postgresql_conf_hot_standby: on
postgresql_conf_hot_standby_feedback: on
postgresql_conf_log_destination: "'stderr'"
postgresql_conf_logging_collector: on
postgresql_conf_log_directory: "'pg_log'"
postgresql_conf_log_filename: "'postgresql-%Y-%m-%d_%H%M%S.log'"
postgresql_conf_log_rotation_age: 1d
postgresql_conf_log_min_duration_statement: 1000
postgresql_conf_log_checkpoints: on
postgresql_conf_log_line_prefix: "'%m %p %u %d %h %v %x %i '"
postgresql_conf_autovacuum: on
postgresql_conf_autovacuum_max_workers: 8
postgresql_conf_autovacuum_vacuum_scale_factor: 0.01
postgresql_conf_autovacuum_analyze_scale_factor: 0.05
postgresql_conf_track_io_timing: on
postgresql_conf_track_functions: pl
